"""
Test User Agent
Run this agent while orchestrator.py is running to test sending a query and receiving output!
"""

from uagents import Agent, Context, Model

# Message schemas matching orchestrator.py
class UserQuery(Model):
    user_id: str
    text: str

class AgentReply(Model):
    text: str

# Address generated by orchestrator.py
ORCHESTRATOR_ADDRESS = "agent1qdt94gldnk8v0rwlnfqr37672hv2ft7m6wy6u4k6nfwk4purne8cx37rc8g"

user_agent = Agent(
    name="user_tester",
    port=8001,
    seed="campus_ai_user_test_seed_999",
    endpoint=["http://127.0.0.1:8001/submit"],
)

@user_agent.on_event("startup")
async def send_query(ctx: Context):
    ctx.logger.info("Sending test query to Orchestrator...")
    # Test query
    query = UserQuery(user_id="student_101", text="When is the exam timetable releasing?")
    await ctx.send(ORCHESTRATOR_ADDRESS, query)

@user_agent.on_message(model=AgentReply)
async def handle_reply(ctx: Context, sender: str, msg: AgentReply):
    ctx.logger.info(f"RECEIVED RESPONSE FROM ORCHESTRATOR: '{msg.text}'")

if __name__ == "__main__":
    user_agent.run()
